### PR TITLE
Add stacktrace as slice

### PR DESCRIPTION
**Pull request by manicar2093**
## Changes

I add a way to show stacktrace as slice. This can be useful when you need to log. (I was not able to log this data in a file without given format, so I thought this would be useful)

## Checklist
- [X] I have checked that there is no similar [pull request](https://github.com/coditory/go-errors/pulls) already submitted
- [X] I have read [contributing.md](https://github.com/coditory/go-errors/blob/main/.github/CONTRIBUTING.md) and applied to the rules
- [X] I have unit tested code changes and performed a self-review

### CODE REVIEW

**Comment by manicar2093** [comment]
Hi, @pmendelski 

How you see this changes? You found it useful to be added? 😃  If I forgot something in the PR tell me and I'll work on it!

**Comment by ogesaku** [comment]
Hey, sorry for taking it so long to answer.

Could you elaborate on "I was not able to log this data in a file without given format". What exactly did you want to achieve? Is available formatting insufficient? Would you like just to format it in a different way? Do you need to have it in a slice for structured logging?

**Comment by manicar2093** [comment]
Hi, @ogesaku.

Don't worry! 😃 

Sure, I want to use stack to be logged with a different logging implementation and show it as JSON. I was using [logrus](https://github.com/sirupsen/logrus) in one project and this logging is not possible due the only way to show stack is using the errors.Format method.

That's why I added StackTraceSlice method to get errors formated as a string slice and be able to added to others implementations or be used in other ways. 😃

**Comment by manicar2093** [comment]
Hi! Won't you use this MR? On that case, could we close it? 😃

**Comment by ogesaku** [comment]
Sorry 😄  closing

**Pull request closed without merging**
